var settings = {
	this.segments = [
		{ label: "+1", functor: 0},
		{ label: "+1", functor: 0},
		{ label: "+1", functor: 0},
		{ label: "+1", functor: 0},
		{ label: "+1", functor: 0},
		{ label: "+1", functor: 0},
		{ label: "+2", functor: 0},
		{ label: "+2", functor: 0},
		{ label: "+2", functor: 0},
		{ label: "+2", functor: 0},
		{ label: "+2", functor: 0},
		{ label: "+3", functor: 0},
		{ label: "+5", functor: 0},
		{ label: "+5", functor: 0},
		{ label: "+5", functor: 0},
		{ label: "+5", functor: 0},
		{ label: "-1", functor: 0},
		{ label: "-1", functor: 0},
		{ label: "-1", functor: 0},
		{ label: "-1", functor: 0},
		{ label: "-2", functor: 0},
		{ label: "-2", functor: 0},
		{ label: "-2", functor: 0},
		{ label: "-2", functor: 0},
		{ label: "-2", functor: 0},
		{ label: "-2", functor: 0},
		{ label: "-2", functor: 0},
		{ label: "-2", functor: 0},
		{ label: "-3", functor: 0},
		{ label: "-3", functor: 0},
		{ label: "-3", functor: 0},
		{ label: "-3", functor: 0},
		{ label: "-3", functor: 0},
		{ label: "-5", functor: 0},
		{ label: "-5", functor: 0},
		{ label: "-5", functor: 0},
		{ label: "Back to 0!", functor: 1},
		{ label: "Back to 0!", functor: 1},
		{ label: "Donate 1 to next guy!", functor: 2},
		{ label: "Double Previous!", functor: 3},
		{ label: "Double Previous!", functor: 3},
		{ label: "Gain 2 rolls!", functor: 4},
		{ label: "Gain 2 rolls!", functor: 4},
		{ label: "Gain a Roll!", functor: 5},
		{ label: "Gain a Roll!", functor: 5},
		{ label: "Lose a Roll!", functor: 6},
		{ label: "Negate Previous!", functor: 7},
		{ label: "Negate Previous!", functor: 7},
	];
};
